---
- hosts: test
  remote_user: root
  tasks: 
  - name: set up /etc/sysctl.d/k8s.conf
    copy: 
      dest: /etc/sysctl.d/k8s.conf
      content: |
        net.ipv4.ip_forward=1
        net.bridge.bridge-nf-call-ip6tables = 1
        net.bridge.bridge-nf-call-iptables = 1    
  - name: load kernel modules
    shell: |
        modprobe br_netfilter
        sysctl --system

