---
- hosts: test
  remote_user: root
  tasks:
  - name: download k8s docker images
    shell: |
      images=(pause-amd64:3.1 pause:3.1 )
      for imageName in ${images[@]} ; do
      if [ $( docker images | grep "{{ lan_registry }}/$imageName" | wc -l ) -eq 0 ]; then
        docker pull ocscaas/$imageName
        docker tag ocscaas/$imageName {{ lan_registry }}/$imageName
        docker push {{ lan_registry }}/$imageName
      fi
      done
      images=(kube-proxy:{{ kubernetes_version }} kube-scheduler:{{ kubernetes_version }} kube-controller-manager:{{ kubernetes_version }} kube-apiserver:{{ kubernetes_version }} etcd:3.3.10)
      for imageName in ${images[@]} ; do
      if [ $( docker images | grep "{{ lan_registry }}/$imageName" | wc -l ) -eq 0 ]; then
        docker pull mirrorgooglecontainers/$imageName
        docker tag mirrorgooglecontainers/$imageName {{ lan_registry }}/$imageName
        docker push {{ lan_registry }}/$imageName
      fi
      done
      docker pull coredns/coredns:1.3.1
      docker tag coredns/coredns:1.3.1 {{ lan_registry }}/coredns:1.3.1
      docker push {{ lan_registry }}/coredns:1.3.1

